#pragma once
#include <stdio.h>
#include <string.h>
#include <iostream>
#include <fstream>
#include <string>
#include <functional>
#include <optional>
#include <stdio.h>
#include <math.h>
#include <algorithm>
#include <vector>
#include <glm/glm.hpp>
#include <glm/gtx/transform.hpp>
#include <glm/gtx/norm.hpp>
#include <glm/gtc/matrix_transform.hpp>
#include <bitset>
#include <thread>
#include <chrono>
#include <mutex>
#include <unordered_map>
#define GLM_ENABLE_EXPERIMENTAL
#include <glm/gtx/hash.hpp>
